// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvxjnghrpgtssbdgxaoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2eGpuZ2hycGd0c3NiZGd4YW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjAwNDEsImV4cCI6MjA2NTQ5NjA0MX0.KA_BSKFPMBHaAcCI0C-V57OU_OgUgmWuOnKXd5r0liA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);